### ISSUE TITLE
entrypoint.sh not found

### ISSUE THREAD

**Issue by HardRock4Life** [lmangani/docker-clickhouse-grafana#2]
Hello! How can I solve this issue?

![image](https://user-images.githubusercontent.com/21273349/132876401-21c04c14-3502-438b-8ebb-0a421581d8d6.png)

**Comment by lmangani** [comment]
Hi @HardRock4Life this repository is VERY obsolete, please do not use it as a reference.
The latest grafana 8.1 should already contain the vertamedia-clickhouse plugin or their [docker compose](https://github.com/Vertamedia/clickhouse-grafana/blob/master/docker-compose.yaml) examples
